---
name: Alien-WiX
version: 0.305207
author:
  - 'Curtis Jewell <csjewell@cpan.org>'
abstract: Installing and finding Windows Installer XML (WiX)
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  Module::Build: 0.21
  Win32API::Registry: 0.30
requires:
  Readonly: 1.03
  Test::More: 0
  Win32::TieRegistry: 0.25
  Win32API::Registry: 0.30
  perl: 5.006
  version: 0.76
build_requires:
  Module::Build: 0.21
recommends:
  Readonly::XS: 1.05
provides:
  Alien::WiX:
    file: lib/Alien/WiX.pm
    version: 0.305207
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
